name: Docker Image CI

on:
  push:
    branches: [new_ui]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'shirsho-12'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
